<div align="center">

# 🌸✨ Anime Explorer ✨🌸

### *Collecting Anime Metadata using the OMDb API*

<img src="https://img.shields.io/badge/Python-3776AB?style=for-the-badge&logo=python&logoColor=white">

<img src="https://img.shields.io/badge/OMDb_API-FF6F61?style=for-the-badge">



<img src="https://img.shields.io/badge/JSON-4B8BBE?style=for-the-badge">

<img src="https://img.shields.io/badge/Pandas-150458?style=for-the-badge&logo=pandas&logoColor=white">

---

### 🌸 "Hard work is worthless for those that don't believe in themselves."
— Naruto 

*"Just as every story shapes its characters, every API response shapes meaningful data."*

</div>

<div style="background:#FDF8FF;border-left:8px solid #C8A2C8;padding:18px;border-radius:15px;">

## 🌷 Project Introduction

In this project, I explored the **OMDb API** to collect information about popular anime titles.

Instead of scraping webpages manually, I connected directly to an API, retrieved structured JSON data, transformed it into a clean DataFrame, and prepared it for further analysis.

This project strengthened my understanding of:

✨ Working with REST APIs

✨ Sending HTTP Requests

✨ Handling JSON Responses

✨ Data Cleaning

✨ Creating Structured Datasets using Pandas

</div>

<div style="background:#FFF7FC;padding:15px;border-radius:12px;">

## Importing requests library🌸


</div>

In [90]:
import requests

<div style="background:#FFF7FC;padding:15px;border-radius:12px;">

## Anime list 


</div>

In [118]:
animes = [
     "Akira",
     "Spirited away",
     "Attack on titan",
      "Grave of the Fireflies",
      "Death note",
    "A Silent Voice",
    "Nausicaa of the Valley of the Wind",
    "Wolf Children",
    "My Neighbor Totoro",
    "The Girl Who Leapt Through Time" ,
    "fullmetal Alchemist" ,
    "Naruto",
    "One piece",
    "Violet evergarden",
    "steins gate",
    "Dr. stone"
]
api_key ="83306ba2"

<div style="background:#F7FCFF;padding:15px;border-radius:12px;">

##  Constructing the API Request and looping through anime list🌐

Creating a dynamic request URL by combining the anime title with the personal API key for authenticated access.

</div>

In [119]:
anime_movie = []
for anime in animes:
   
    url = f"https://www.omdbapi.com/?t={anime}&apikey={api_key}"
    response = requests.get(url)
    data = response.json()
    if data['Response'] == 'True':
        anime_movie.append({
            "Title": data['Title'],
            "Year": data['Year'],
            "Genre": data['Genre'],
            "IMDb Rating": data['imdbRating'],
            "Director": data['Director'],
            'plot':data['Plot']
        })

<div style="background:#FFFDF6;border-left:8px solid #D8BFD8;padding:18px;border-radius:15px;">

# 🌸✨ Extracted Relevant Data ✨🌸

Carefully selecting only the most meaningful information from each API response to create a clean, structured, and analysis-ready dataset.

### 📌 Fields Extracted

🎬 Title

📅 Release Year

🎭 Genre

⭐ IMDb Rating

🎥 Director

📝 Plot Summary

*"Not all data is valuable—only the data that tells a story."* 🌸

</div>

In [120]:
anime_movie

[{'Title': 'Akira',
  'Year': '1988',
  'Genre': 'Animation, Action, Drama',
  'IMDb Rating': '8.0',
  'Director': 'Katsuhiro Ôtomo',
  'plot': 'A secret military project endangers Neo-Tokyo when it turns a teenage biker gang member into a rampaging psychic psychopath who can only be stopped by his best friend.'},
 {'Title': 'Spirited Away',
  'Year': '2003',
  'Genre': 'Animation, Adventure, Family',
  'IMDb Rating': '8.6',
  'Director': 'Hayao Miyazaki',
  'plot': "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts."},
 {'Title': 'Attack on Titan',
  'Year': '2013–2023',
  'Genre': 'Animation, Action, Adventure',
  'IMDb Rating': '9.1',
  'Director': 'N/A',
  'plot': 'In a world where humanity shelters behind towering walls from man-eating Titans, a determined teen joins the elite Survey Corps to fight the giants and uncover the secrets of their origin.'},
 {'Title': 'Grave of the Fireflies',
  'Year': '1989',
  'Genre': 'Animation, Drama, War',
  'IMDb Rating': '8.5',
  'Director': 'Isao Takahata',
  'plot': 'A young boy and his little sister struggle to survive in Japan during World War II.'},
 {'Title': 'Death Note',
  'Year': '2006–2007',
  'Genre': 'Animation, Crime, Drama',
  'IMDb Rating': '8.9',
  'Director': 'N/A',
  'plot': 'An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.'},
 {'Title': 'A Silent Voice',
  'Year': '2017',
  'Genre': 'Short',
  'IMDb Rating': 'N/A',
  'Director': 'Milad Mohebbian',
  'plot': 'A silent voice is for voices that are not heard before! For people who die in silence! And the only voice that they hear is the Fire sound.'},
 {'Title': 'Behind the Microphone: Nausicaa of the Valley of the Wind',
  'Year': '2005',
  'Genre': 'Short',
  'IMDb Rating': '7.8',
  'Director': 'N/A',
  'plot': 'N/A'},
 {'Title': 'Wolf Children',
  'Year': '2012',
  'Genre': 'Animation, Drama, Family',
  'IMDb Rating': '8.1',
  'Director': 'Mamoru Hosoda',
  'plot': 'After her werewolf lover unexpectedly dies in an accident, a young woman must find ways to raise their werewolf son and daughter while keeping their trait hidden from society.'},
 {'Title': 'My Neighbor Totoro',
  'Year': '1988',
  'Genre': 'Animation, Adventure, Comedy',
  'IMDb Rating': '8.1',
  'Director': 'Hayao Miyazaki',
  'plot': 'When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.'},
 {'Title': 'The Girl Who Leapt Through Time',
  'Year': '2006',
  'Genre': 'Animation, Adventure, Comedy',
  'IMDb Rating': '7.6',
  'Director': 'Mamoru Hosoda',
  'plot': 'A high-school girl named Makoto acquires the power to travel back in time, and decides to use it for her own personal benefits. Little does she know that she is affecting the lives of others just as much as she is her own.'},
 {'Title': 'Fullmetal Alchemist',
  'Year': '2003–2004',
  'Genre': 'Animation, Action, Adventure',
  'IMDb Rating': '8.5',
  'Director': 'N/A',
  'plot': "When a failed alchemical ritual leaves brothers Edward and Alphonse Elric with severely damaged bodies, they begin searching for the one thing that can save them: the fabled philosopher's stone."},
 {'Title': 'Naruto',
  'Year': '2002–2007',
  'Genre': 'Animation, Action, Adventure',
  'IMDb Rating': '8.4',
  'Director': 'N/A',
  'plot': "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village's leader and strongest ninja."},
 {'Title': 'One Piece',
  'Year': '1999–',
  'Genre': 'Animation, Action, Adventure',
  'IMDb Rating': '9.0',
  'Director': 'N/A',
  'plot': 'Monkey D. Luffy, a pirate with rubber powers, forms the Straw Hat crew and sails the Grand Line, battling rivals and the World Government on a quest for the legendary treasure One Piece and the title of Pirate King.'},
 {'Title': 'Violet Evergarden',
  'Year': '2018',
  'Genre': 'Animation, Drama, Fantasy',
  'IMDb Rating': '8.4',
  'Director': 'N/A',
  'plot': "In the aftermath of a great war, Violet Evergarden, a young female ex-soldier, gets a job at a writers' agency and goes on assignments to create letters that can connect people."},
 {'Title': 'Steins;Gate',
  'Year': '2011–2015',
  'Genre': 'Animation, Comedy, Drama',
  'IMDb Rating': '8.8',
  'Director': 'N/A',
  'plot': 'After discovering time travel, a university student and his colleagues must use their knowledge of it to stop an evil organization and their diabolical plans.'},
 {'Title': 'Dr. Stone',
  'Year': '2019–',
  'Genre': 'Animation, Action, Adventure',
  'IMDb Rating': '8.1',
  'Director': 'N/A',
  'plot': 'High schooler Taiju awakens from petrification millennia after a blinding light turned humanity to stone. He finds his scientific genius friend Senku working on a plan to rebuild civilization using science.'}]

<div style="background:#FDF8FF;border-left:8px solid #C8A2C8;padding:18px;border-radius:15px;">

# 🌸✨ Creating the DataFrame ✨🌸

Transforming the collected anime records into a structured **Pandas DataFrame**, making the dataset organized, searchable, and ready for analysis.

✨ From scattered API responses to one unified story.

---



*"Just as memories come together to tell a story, every row in this DataFrame becomes a chapter of the anime universe."* 🌸

</div>

In [121]:
import pandas  as pd
df = pd.DataFrame(anime_movie)
df

,Title,Year,Genre,IMDb Rating,Director,plot
0,Akira,1988,"Animation, Action, Drama",8.0,Katsuhiro Ôtomo,A secret military project endangers Neo-Tokyo ...
1,Spirited Away,2003,"Animation, Adventure, Family",8.6,Hayao Miyazaki,"During her family's move to the suburbs, a sul..."
2,Attack on Titan,2013–2023,"Animation, Action, Adventure",9.1,N/A,In a world where humanity shelters behind towe...
3,Grave of the Fireflies,1989,"Animation, Drama, War",8.5,Isao Takahata,A young boy and his little sister struggle to ...
4,Death Note,2006–2007,"Animation, Crime, Drama",8.9,N/A,An intelligent high school student goes on a s...
5,A Silent Voice,2017,Short,N/A,Milad Mohebbian,A silent voice is for voices that are not hear...
6,Behind the Microphone: Nausicaa of the Valley ...,2005,Short,7.8,N/A,N/A
7,Wolf Children,2012,"Animation, Drama, Family",8.1,Mamoru Hosoda,After her werewolf lover unexpectedly dies in ...
8,My Neighbor Totoro,1988,"Animation, Adventure, Comedy",8.1,Hayao Miyazaki,When two girls move to the country to be near ...
9,The Girl Who Leapt Through Time,2006,"Animation, Adventure, Comedy",7.6,Mamoru Hosoda,A high-school girl named Makoto acquires the p...
10,Fullmetal Alchemist,2003–2004,"Animation, Action, Adventure",8.5,N/A,When a failed alchemical ritual leaves brother...
11,Naruto,2002–2007,"Animation, Action, Adventure",8.4,N/A,"Naruto Uzumaki, a mischievous adolescent ninja..."
12,One Piece,1999–,"Animation, Action, Adventure",9.0,N/A,"Monkey D. Luffy, a pirate with rubber powers, ..."
13,Violet Evergarden,2018,"Animation, Drama, Fantasy",8.4,N/A,"In the aftermath of a great war, Violet Everga..."
14,Steins;Gate,2011–2015,"Animation, Comedy, Drama",8.8,N/A,"After discovering time travel, a university st..."
15,Dr. Stone,2019–,"Animation, Action, Adventure",8.1,N/A,High schooler Taiju awakens from petrification...

In [122]:
#as rating column is string nd have some n/a values therefore we can't use .astype(float), instead we use to_numeric which can handle error and then we can use fill na too...
df['IMDb Rating'] = pd.to_numeric(df['IMDb Rating'], errors='coerce')
df

,Title,Year,Genre,IMDb Rating,Director,plot
0,Akira,1988,"Animation, Action, Drama",8.0,Katsuhiro Ôtomo,A secret military project endangers Neo-Tokyo ...
1,Spirited Away,2003,"Animation, Adventure, Family",8.6,Hayao Miyazaki,"During her family's move to the suburbs, a sul..."
2,Attack on Titan,2013–2023,"Animation, Action, Adventure",9.1,N/A,In a world where humanity shelters behind towe...
3,Grave of the Fireflies,1989,"Animation, Drama, War",8.5,Isao Takahata,A young boy and his little sister struggle to ...
4,Death Note,2006–2007,"Animation, Crime, Drama",8.9,N/A,An intelligent high school student goes on a s...
5,A Silent Voice,2017,Short,NaN,Milad Mohebbian,A silent voice is for voices that are not hear...
6,Behind the Microphone: Nausicaa of the Valley ...,2005,Short,7.8,N/A,N/A
7,Wolf Children,2012,"Animation, Drama, Family",8.1,Mamoru Hosoda,After her werewolf lover unexpectedly dies in ...
8,My Neighbor Totoro,1988,"Animation, Adventure, Comedy",8.1,Hayao Miyazaki,When two girls move to the country to be near ...
9,The Girl Who Leapt Through Time,2006,"Animation, Adventure, Comedy",7.6,Mamoru Hosoda,A high-school girl named Makoto acquires the p...
10,Fullmetal Alchemist,2003–2004,"Animation, Action, Adventure",8.5,N/A,When a failed alchemical ritual leaves brother...
11,Naruto,2002–2007,"Animation, Action, Adventure",8.4,N/A,"Naruto Uzumaki, a mischievous adolescent ninja..."
12,One Piece,1999–,"Animation, Action, Adventure",9.0,N/A,"Monkey D. Luffy, a pirate with rubber powers, ..."
13,Violet Evergarden,2018,"Animation, Drama, Fantasy",8.4,N/A,"In the aftermath of a great war, Violet Everga..."
14,Steins;Gate,2011–2015,"Animation, Comedy, Drama",8.8,N/A,"After discovering time travel, a university st..."
15,Dr. Stone,2019–,"Animation, Action, Adventure",8.1,N/A,High schooler Taiju awakens from petrification...

In [123]:
#fill na:
df['IMDb Rating'] = df['IMDb Rating'].fillna(0)
df

,Title,Year,Genre,IMDb Rating,Director,plot
0,Akira,1988,"Animation, Action, Drama",8.0,Katsuhiro Ôtomo,A secret military project endangers Neo-Tokyo ...
1,Spirited Away,2003,"Animation, Adventure, Family",8.6,Hayao Miyazaki,"During her family's move to the suburbs, a sul..."
2,Attack on Titan,2013–2023,"Animation, Action, Adventure",9.1,N/A,In a world where humanity shelters behind towe...
3,Grave of the Fireflies,1989,"Animation, Drama, War",8.5,Isao Takahata,A young boy and his little sister struggle to ...
4,Death Note,2006–2007,"Animation, Crime, Drama",8.9,N/A,An intelligent high school student goes on a s...
5,A Silent Voice,2017,Short,0.0,Milad Mohebbian,A silent voice is for voices that are not hear...
6,Behind the Microphone: Nausicaa of the Valley ...,2005,Short,7.8,N/A,N/A
7,Wolf Children,2012,"Animation, Drama, Family",8.1,Mamoru Hosoda,After her werewolf lover unexpectedly dies in ...
8,My Neighbor Totoro,1988,"Animation, Adventure, Comedy",8.1,Hayao Miyazaki,When two girls move to the country to be near ...
9,The Girl Who Leapt Through Time,2006,"Animation, Adventure, Comedy",7.6,Mamoru Hosoda,A high-school girl named Makoto acquires the p...
10,Fullmetal Alchemist,2003–2004,"Animation, Action, Adventure",8.5,N/A,When a failed alchemical ritual leaves brother...
11,Naruto,2002–2007,"Animation, Action, Adventure",8.4,N/A,"Naruto Uzumaki, a mischievous adolescent ninja..."
12,One Piece,1999–,"Animation, Action, Adventure",9.0,N/A,"Monkey D. Luffy, a pirate with rubber powers, ..."
13,Violet Evergarden,2018,"Animation, Drama, Fantasy",8.4,N/A,"In the aftermath of a great war, Violet Everga..."
14,Steins;Gate,2011–2015,"Animation, Comedy, Drama",8.8,N/A,"After discovering time travel, a university st..."
15,Dr. Stone,2019–,"Animation, Action, Adventure",8.1,N/A,High schooler Taiju awakens from petrification...

In [124]:
#as some directors are unknown too:
df['Director'] = df['Director'].replace('N/A', 'unknown')
df

,Title,Year,Genre,IMDb Rating,Director,plot
0,Akira,1988,"Animation, Action, Drama",8.0,Katsuhiro Ôtomo,A secret military project endangers Neo-Tokyo ...
1,Spirited Away,2003,"Animation, Adventure, Family",8.6,Hayao Miyazaki,"During her family's move to the suburbs, a sul..."
2,Attack on Titan,2013–2023,"Animation, Action, Adventure",9.1,unknown,In a world where humanity shelters behind towe...
3,Grave of the Fireflies,1989,"Animation, Drama, War",8.5,Isao Takahata,A young boy and his little sister struggle to ...
4,Death Note,2006–2007,"Animation, Crime, Drama",8.9,unknown,An intelligent high school student goes on a s...
5,A Silent Voice,2017,Short,0.0,Milad Mohebbian,A silent voice is for voices that are not hear...
6,Behind the Microphone: Nausicaa of the Valley ...,2005,Short,7.8,unknown,N/A
7,Wolf Children,2012,"Animation, Drama, Family",8.1,Mamoru Hosoda,After her werewolf lover unexpectedly dies in ...
8,My Neighbor Totoro,1988,"Animation, Adventure, Comedy",8.1,Hayao Miyazaki,When two girls move to the country to be near ...
9,The Girl Who Leapt Through Time,2006,"Animation, Adventure, Comedy",7.6,Mamoru Hosoda,A high-school girl named Makoto acquires the p...
10,Fullmetal Alchemist,2003–2004,"Animation, Action, Adventure",8.5,unknown,When a failed alchemical ritual leaves brother...
11,Naruto,2002–2007,"Animation, Action, Adventure",8.4,unknown,"Naruto Uzumaki, a mischievous adolescent ninja..."
12,One Piece,1999–,"Animation, Action, Adventure",9.0,unknown,"Monkey D. Luffy, a pirate with rubber powers, ..."
13,Violet Evergarden,2018,"Animation, Drama, Fantasy",8.4,unknown,"In the aftermath of a great war, Violet Everga..."
14,Steins;Gate,2011–2015,"Animation, Comedy, Drama",8.8,unknown,"After discovering time travel, a university st..."
15,Dr. Stone,2019–,"Animation, Action, Adventure",8.1,unknown,High schooler Taiju awakens from petrification...

<div align="center" style="background:#F9F4FF;border-left:8px solid #C8A2C8;padding:24px;border-radius:18px;">

# 🌸✨ Project Complete ✨🌸

From raw API responses to a structured dataset, every step of this project strengthened my understanding of real-world data collection.

This isn't just an anime dataset—

It's another milestone in my journey through AI, Machine Learning, and Data Science.

---

### 🌸 "A lesson without pain is meaningless."
### — Fullmetal Alchemist: Brotherhood

## 💜 *Every project is proof that consistency creates excellence.*



</div>